# Generated by Django 2.0.4 on 2019-06-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('order_id', models.IntegerField(verbose_name='章节ID')),
                ('name', models.CharField(max_length=20, verbose_name='章节名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('discrib', models.CharField(max_length=20, verbose_name='课程描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价钱')),
                ('watched', models.IntegerField(verbose_name='观看人数')),
                ('learned', models.IntegerField(verbose_name='收藏人数')),
                ('score', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='热度值')),
            ],
            options={
                'ordering': ('score',),
            },
        ),
        migrations.CreateModel(
            name='CourseCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('order_id', models.IntegerField(verbose_name='小节ID')),
                ('name', models.CharField(max_length=20, verbose_name='小节名称')),
                ('detail_url', models.SlugField(verbose_name='内容地址')),
                ('choices', models.IntegerField(verbose_name='小节分类')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chapter', verbose_name='关联章节')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=20, verbose_name='课程分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='所属课程'),
        ),
    ]
