# Generated by Django 2.0.4 on 2019-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_pay',
            field=models.IntegerField(default=1, verbose_name='是否付费'),
            preserve_default=False,
        ),
    ]
