# Generated by Django 2.0.4 on 2019-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190626_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learned',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='热度值'),
        ),
        migrations.AlterField(
            model_name='course',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='观看人数'),
        ),
    ]
