# Generated by Django 2.0.4 on 2019-06-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190626_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField(verbose_name='课程id')),
                ('contents', models.CharField(max_length=225, verbose_name='内容')),
                ('from_uid', models.IntegerField(verbose_name='评论用户')),
                ('to_uid', models.IntegerField(verbose_name='接受用户')),
            ],
            options={
                'verbose_name_plural': '评论表',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
    ]
