# Generated by Django 2.0.4 on 2019-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_content_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='from_uid',
            field=models.IntegerField(verbose_name='评论主题用户'),
        ),
        migrations.AlterField(
            model_name='content',
            name='to_uid',
            field=models.IntegerField(default=0, verbose_name='回复用户'),
        ),
    ]
